//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int AssignmentId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> SubTaskId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public string ScheduleTime { get; set; }
        public Nullable<int> Stage { get; set; }
    }
}
