//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedPM
    {
        public int AssignedPMID { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public string EmpPosition { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
