//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditor
    {
        public int CreditorId { get; set; }
        public string CreditorName { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public string CreditDescription { get; set; }
    }
}
