//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpMeeting
    {
        public int EmpMeetId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> MeetingId { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
