//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InepVariance
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string MonthVarianceReason { get; set; }
        public string MonthCorrectiveAction { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string YearVarianceReason { get; set; }
        public string YearCorrectiveAction { get; set; }
        public string OtherComments { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ReportNumber { get; set; }
        public Nullable<double> MunicipalityApproval { get; set; }
        public Nullable<double> Pre_Engineering { get; set; }
        public Nullable<double> Design { get; set; }
        public Nullable<double> Procurement { get; set; }
        public Nullable<double> Construction { get; set; }
        public Nullable<double> CloseUp { get; set; }
        public Nullable<double> AmountRecieved { get; set; }
    }
}
