//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTbl
    {
        public int InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.DateTime> Invoicedate { get; set; }
        public string StatusIvo { get; set; }
        public string NoteMessage { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Item { get; set; }
        public Nullable<int> SubTaskId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
