//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int LeaveId { get; set; }
        public System.DateTime AppDate { get; set; }
        public string Duration { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string ApplicantName { get; set; }
        public string ReasonForApplying { get; set; }
        public Nullable<System.DateTime> Fromdate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public string Comment { get; set; }
        public string FeedMessage { get; set; }
    }
}
