//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogisticBooking
    {
        public int LogisticBookingId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ReasonForBooking { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> DateAttended { get; set; }
        public Nullable<double> Salary { get; set; }
    }
}
