//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int MeetingId { get; set; }
        public string Subject { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ThemeColor { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string NewClientEmail { get; set; }
        public System.DateTime TDate { get; set; }
        public string Description { get; set; }
        public string MeetingNo { get; set; }
    }
}
