//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public string WorkDescription { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public Nullable<int> TargetedHours { get; set; }
        public Nullable<int> EmpId { get; set; }
    }
}
