//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<double> GrossAmount { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public Nullable<double> HourRate { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<int> OverTimeHours { get; set; }
    }
}
