//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTask
    {
        public int SubTaskId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string SubName { get; set; }
        public Nullable<int> NoOfDays { get; set; }
    }
}
