//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> LogisticBookId { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public string item { get; set; }
        public Nullable<double> Price { get; set; }
        public string SlipPath { get; set; }
    }
}
